USE CJSDB;

/*
INSERT INTO CUSTOMERS (F_NAME, L_NAME, PHONE, ADDR, ST, ZIPCODE) VALUES ('EVE', 'LIN', '123456790', '123456asdds','MO', '12345');
INSERT INTO CUSTOMERS (F_NAME, L_NAME, PHONE, ADDR, ST, ZIPCODE) VALUES ('MALKA', 'IDKRAY', '0987654321', '32AS4D1AS3D','MO', '54321');
INSERT INTO TRANSACTIONS (C_ID, T_DATE_TIME, T_TOTAL) VALUES (1, NOW(), 999.99);
INSERT INTO TRANSACTIONS (C_ID, T_DATE_TIME, T_TOTAL) VALUES (2, NOW(), 0.99);

INSERT INTO PAYMENT_METHODS (PM_NAME, PM_DESC) VALUES ('CASH', 'CASH PAYMENTS');
INSERT INTO PAYMENT_METHODS (PM_NAME, PM_DESC) VALUES ('STRIPE', 'CARD PAYMENTS THROUGH STRIPE');
INSERT INTO PAYMENT_METHODS (PM_NAME, PM_DESC) VALUES ('CHECK', 'CHECK PAYMENTS');
*/

INSERT INTO CUSTOMERS (F_NAME, L_NAME, PHONE, ADDR, ST, ZIPCODE) VALUES ('KAMAL', 'HAROUN', '000000000', '32ASDASDGFD','MO', '59654');

COMMIT;